change the version number to v0.5.0 (#44)
* Update README.md

Current v0.3.0 supporting NCSDK v1.07.06 is on master branch. devel branch is the development branch for the next release.

* find the catkin package before calling catkin_package() function in cmake file. Without this, the catkin tools from python-catkin-tools(not catkin_make) will report build issue. (#2)

* use x86 intrinsic to optimize the float conversion

* use x86 intrinsic to optimize the float conversion

* fix the missing conversion for intrinsics usage

* Support NCSDKv1.09.00

* Support NCSDK v1.09.00

1. change the launch file
2. update APIs to replace deprecated APIs
3. statistic information is passed by argument instead of txt file

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update README.md

support NCSDK v1.09.00

* Update README.md

* Support realsense d400 series camera

* support realsense d400 series camera

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update README.md

* Update README.md

* change the resolution of rs_d400 and install target to install folder

* support realsense d400 series camera

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update README.md

* change default w/h and install target to install folder

width=640, height=480

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Skip inferring when no subscriber

Signed-off-by: Peter Han <peter.han@intel.com>

* Init member variables of NcsImpl with proper value

Signed-off-by: Peter Han <peter.han@intel.com>

* Quick fix a build issue


* quick fix a build issue

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* change version in package.xml to V0.4.0

* support realsense d400 series camera

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update README.md

* change default w/h and install target to install folder

width=640, height=480

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* change the version in package.xml to v0.4.0

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update README.md

* Add a changelog file

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update CHANGELOG.rst

* add a changelog file

* Update CHANGELOG.rst

* enable tiny yolo on both ncs_image and ncs_stream

* support realsense d400 series camera

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update README.md

* enable tiny yolo both on ncs_image and ncs_stream

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update ncs_usbcam_detector.launch

* change the default graph path in launch files

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update README.md

* Fix compile issue on Intel old platforms when using x86 intrinsic optimization

Add "mf16c" compiling flag for platform earlier than Ivy Bridge.

Signed-off-by: Chao Li <chao1.li@intel.com>

* format code according to ros coding guide

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* refactor code (#23)

* refactor code

1. redesign the classes to make transaction logic more clear.
2. remove the duplicated attributes in different classes.
3. optimize code structure
4. further change coding style according to ROS and google coding guide

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update README.md

* change permission of files and folders

Signed-off-by: Huang,Xiaojun <xiaojun.huang@intel.com>

* change the format of category files (#24)

change the format of category files from dos to unix to avoid unrecognized chars

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* remove zr300 launch file

stop supporting realsense zr300 camera due to its EOL.

* remove deprecated launch files

* remove deprecated launch files

Use yaml files to configure different CNN models, which can greatly reduce the redundency of launch files.
Besides, use if clause to judge different kinds of cameras in launch files also can reduce the number of launch files.

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update README.md

* Show exception messages (#27)

* enable mobilenet_ssd support

* enable mobilenet_ssd support

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update alexnet.yaml

* Update README.md

* change the mobilenet_ssd path to the one in ncappzoo

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* support inception_v1

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* support inception_v2

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* support inception_v3

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* fix the issue of "undefined reference to opencv"

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* support inception_v4

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* support mobilenet

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* fix the incorrect inference result from mobilenetssd

ignore the locaton values which are lower than 0 or higher than image range

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* add test images

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Reorganize readme file

* seperate classification and detection description

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update README.md

* Change title of description files with more meaningful names (#39)

* change the title of description files with more meaningful names

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>

* Update image_classification.md

* minor change readme file and other description files for v0.5.0 release

* Update image_classification.md

* Update video_classification.md

* Update image_detection.md

* Update video_detection.md

* Update README.md

* change the version number to v0.5.0 (#43)

Signed-off-by: Xiaojun Huang <xiaojun.huang@intel.com>